auth_enabled: false

server:
  http_listen_port: 3200


distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  # Cuando una traza queda inactiva 'trace_idle_period', se cierra el bloque
  trace_idle_period: 10s
  max_block_bytes: 1048576  
  max_block_duration: 5m

compactor:
  compaction:
    # Retención (elimina bloques más antiguos que este periodo)
    block_retention: 24h

# Almacenamiento local en disco (single-node)
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
